### ISSUE TITLE
Problem with the Argos Tracking Utility

### ISSUE THREAD

**Issue by bernmang** [subhacom/argos#1]
I seem to have successfully trained the YOLACT backbone network within Google Colab (since I do not have a GPU). I am now trying to use my trained network within the argos_track utility to analyse some locust videos. However, every time I press play within the GUI, it collapses and no tracking occurs.

Here is the code within the Anaconda Prompt:
(track) C:\Users\Berni>python -m argos_track
Loaded C-utilities with pyximport
Loaded C-function for video capture.
WARNING: CUDA not supported in this installation of PyTorch
INFO:root:Output file "C:/Users/Berni/Videos/2013-08-01_Leics_greg/L.greg-0001-L.mp4.h5"
INFO:root:No segmentation data. Not writing file.
INFO:root:First frame read @ 2022-11-11 09:03:18.462437
Use classes set()
C:\Users\Berni\anaconda3\envs\track\lib\site-packages\torch\jit\_recursive.py:238: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
C:\Users\Berni\anaconda3\envs\track\lib\site-packages\torch\jit\_recursive.py:238: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
C:\Users\Berni\anaconda3\envs\track\lib\site-packages\torch\jit\_recursive.py:238: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
Starting at first frame
Traceback (most recent call last):
  File "C:\Users\Berni\anaconda3\envs\track\lib\site-packages\argos\vwidget.py", line 458, in playVideo
    self.timer.start(t)
TypeError: arguments did not match any overloaded call:
  start(self, int): argument 1 has unexpected type 'float'
  start(self): too many arguments

**Comment by subhacom** [comment]
Thank for reporting this. This was because the method `QTimer.start()` takes an integer but I was passing a float, which, in the systems we tested, gets automatically converted. Now I have tried to fix the problem. Please test by installing `argos` from the branch `Fix_1_playtimer` on github like this:

`pip install git+https://github.com/subhacom/argos.git@Fix_1_playtimer`

**Comment by bernmang** [comment]
I've tried it and I'm unfortunately getting the same TypeError

**Comment by subhacom** [comment]
That's strange.  I created and uploaded a new package with the bugfix. Can you please try uninstalling and then installing again? Like this:
```
pip uninstall argos_toolkit
pip uninstall argos_tracker

pip install argos_toolkit
pip install argos_tracker

```

Also, please take a look at the file `{your-site-packages-directory}/argos/vwidget.py`
( which, for example, on my Anaconda conda environment is `c:/Users/{myusername}/Anaconda3/envs/{environment-name}/Lib/site-packages/argos/vwidget.py`, and in your case should be (according to the stack trace)
`C:\Users\Berni\anaconda3\envs\track\lib\site-packages\argos\vwidget.py`)
line 459 and the following ones has this code:
```
            t = int(np.round(1000.0 / self.video_reader.fps))
            t = 10 if t < 1 else t
            self.timer.start(t)
```

**Comment by bernmang** [comment]
It's working now thank you very much for the help!
